# Generated by Django 4.2.30 on 2026-09-30 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=255)),
                ('target_role', models.CharField(blank=True, max_length=255)),
                ('template', models.CharField(choices=[('classic', 'Classic ATS'), ('modern', 'Modern Professional'), ('developer', 'Developer')], default='classic', max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('professional_title', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.URLField(blank=True, max_length=500)),
                ('github', models.URLField(blank=True, max_length=500)),
                ('portfolio', models.URLField(blank=True, max_length=500)),
                ('career_objective', models.TextField(blank=True)),
                ('professional_summary', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('score', models.IntegerField(default=0)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('target_job_description', models.TextField(blank=True)),
                ('tailored_suggestions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
